# Generated by Django 4.1.6 on 2023-06-20 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='ex: Car, bike, moto...', max_length=30, null=True)),
                ('brand', models.CharField(max_length=30, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(help_text='ex: 6347LMP', max_length=20, null=True)),
                ('buying_date', models.DateField(blank=True, null=True)),
                ('buying_price', models.PositiveIntegerField(blank=True, null=True)),
                ('has_been_bought_new', models.BooleanField(blank=True, null=True)),
                ('has_on_going_credit', models.BooleanField(blank=True, default=False, null=True)),
                ('has_on_going_leasing', models.BooleanField(blank=True, default=False, null=True)),
                ('last_itv_date', models.DateField(blank=True, null=True)),
                ('next_itv_date', models.DateField(blank=True, null=True)),
                ('comments', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportation_asset', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Assets',
                'ordering': ['type', 'brand', 'model'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.FileField(upload_to='static/files')),
                ('access_to_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportation_files', to='transportation.asset')),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
    ]
