version: '3'

services:
  # Backend API service
  backend:
    build: 
      context: ./jarvis
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - backend_data:/app/data
    env_file:
      - ./jarvis/.env
    expose:
      - 8000
    networks:
      - app_network

  # Frontend service
  frontend:
    build: 
      context: ./UI
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    expose:
      - 80
    networks:
      - app_network

  # Nginx web server (use the existing configuration)
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./UI/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

volumes:
  static_volume:
  backend_data:

networks:
  app_network:
    driver: bridge
