# Generated by Django 4.1.6 on 2023-06-20 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='nickname you want to give to this asset', max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('buying_date', models.DateField(blank=True, null=True)),
                ('buying_price', models.PositiveIntegerField(blank=True, null=True)),
                ('has_on_going_mortgage', models.BooleanField(blank=True, null=True)),
                ('is_rented', models.BooleanField(blank=True, null=True)),
                ('is_our_living_house', models.BooleanField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, help_text="ex: {'notary_number': 112345, ...", null=True)),
                ('results_by_year', models.JSONField(blank=True, null=True)),
                ('bank_accounts', models.ManyToManyField(blank=True, related_name='asset', related_query_name='asset', to='finances.bankaccount')),
            ],
            options={
                'verbose_name_plural': 'Assets',
                'ordering': ['owner', 'nickname', 'buying_date'],
            },
        ),
        migrations.CreateModel(
            name='CoproManagementCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('personal_email_used', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_app_company', models.CharField(blank=True, help_text='ex: myfoncia.com', max_length=70, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Copro Management Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.FileField(upload_to='static/files')),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='RentingManagementCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('personal_email_used', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_app_company', models.CharField(blank=True, help_text='ex: myfoncia.com', max_length=70, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Renting Management Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.file')),
            ],
            bases=('real_estate.file',),
        ),
        migrations.CreateModel(
            name='FileBill',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.file')),
            ],
            bases=('real_estate.file',),
        ),
        migrations.CreateModel(
            name='FileCoPro',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.file')),
            ],
            bases=('real_estate.file',),
        ),
        migrations.CreateModel(
            name='FileMortgage',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.file')),
            ],
            bases=('real_estate.file',),
        ),
        migrations.CreateModel(
            name='FileRenting',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.file')),
            ],
            bases=('real_estate.file',),
        ),
        migrations.CreateModel(
            name='FileTenant',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.file')),
            ],
            bases=('real_estate.file',),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_type', models.CharField(max_length=50, null=True)),
                ('id_number', models.CharField(max_length=50, null=True)),
                ('bank_account_IBAN', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_recipient', models.CharField(blank=True, max_length=100, null=True)),
                ('rental_starting_date', models.DateField(null=True)),
                ('rental_ending_date', models.DateField(null=True)),
                ('deposit_amount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_actual_tenant', models.BooleanField(null=True)),
                ('has_guarantee', models.BooleanField(blank=True, default=False, null=True)),
                ('comments', models.JSONField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='real_estate.asset')),
            ],
            options={
                'verbose_name_plural': 'Tenants',
                'ordering': ['asset', 'is_actual_tenant', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RentingManagementContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('is_management_active', models.BooleanField(blank=True, null=True)),
                ('annual_results', models.JSONField(blank=True, help_text="ex: {'2020': {'expenses': 1400, 'income': 9000, 'net': 7600}}", null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='real_estate.rentingmanagementcompany')),
            ],
            options={
                'verbose_name_plural': 'Renting Managements',
                'ordering': ['is_management_active', 'company__name', 'asset'],
            },
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('rate_renegociations', models.JSONField(blank=True, help_text="ex: {'2020': 2%, '2021': 1.8%}", null=True)),
                ('annual_interests', models.JSONField(blank=True, help_text="ex: {'2020': 2500, '2021': 2200}", null=True)),
                ('annual_capital_refund', models.JSONField(blank=True, help_text="ex: {'2020': 4000, '2021': 4300}", null=True)),
                ('capital_due_end_of_year', models.JSONField(blank=True, help_text="ex: {'2020': 112345, '2021': 108356}", null=True)),
                ('asset', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mortgage', to='real_estate.asset')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.bankaccount')),
            ],
            options={
                'verbose_name_plural': 'Mortgages',
                'ordering': ['asset', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CoproManagementContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('is_management_active', models.BooleanField(blank=True, null=True)),
                ('annual_expenses', models.JSONField(blank=True, help_text="ex: {'2020': {'fixed': 1400, 'refurbishment': 300, 'other': 12, 'payment_delay': 100}}", null=True)),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copro_contract', to='real_estate.copromanagementcompany')),
            ],
            options={
                'verbose_name_plural': 'Copro Management Contracts',
                'ordering': ['company__name', 'is_management_active'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_name', models.CharField(help_text='Give a meaningfull name at this bill', max_length=50, null=True)),
                ('is_tax_deductible', models.BooleanField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, help_text='price including tax', null=True)),
                ('tax', models.FloatField(blank=True, help_text='tax price', null=True)),
                ('price_without_tax', models.FloatField(blank=True, help_text='price without tax', null=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='real_estate.asset')),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bills',
                'ordering': ['asset', 'is_tax_deductible', 'client_name', 'bill_name', 'date', 'total_price', 'tax', 'price_without_tax'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='copro_contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='real_estate.copromanagementcontract'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_asset', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='renting_contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='real_estate.rentingmanagementcontract'),
        ),
    ]
