# Generated by Django 4.1.6 on 2023-06-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '0001_initial'),
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tax_management',
            field=models.ForeignKey(blank=True, help_text='this asset taxes are managed by a company?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='tax.taxmanagementcontract'),
        ),
        migrations.AddField(
            model_name='filetenant',
            name='access_to_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RE_tenant_files', to='real_estate.tenant'),
        ),
        migrations.AddField(
            model_name='filerenting',
            name='access_to_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RE_renting_files', to='real_estate.rentingmanagementcontract'),
        ),
        migrations.AddField(
            model_name='filemortgage',
            name='access_to_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RE_mortgage_files', to='real_estate.mortgage'),
        ),
        migrations.AddField(
            model_name='filecopro',
            name='access_to_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RE_copro_files', to='real_estate.copromanagementcontract'),
        ),
        migrations.AddField(
            model_name='filebill',
            name='access_to_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RE_bill_files', to='real_estate.bill'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='access_to_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RE_asset_files', to='real_estate.asset'),
        ),
    ]
