# Generated by Django 4.1.6 on 2023-06-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_alter_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='rental_ending_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
