# Generated by Django 4.1.6 on 2023-07-12 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_utilitysupplier_copromanagementcontract_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HollydaysPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('personal_email_used', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_app_company', models.CharField(blank=True, help_text='ex: myfoncia.com', max_length=70, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hollydays Platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HollydaysReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('number_of_nights', models.DateField(blank=True, null=True)),
                ('received_money', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='real_estate.asset')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='real_estate.hollydaysplatform')),
            ],
            options={
                'verbose_name_plural': 'Hollydays Reservations',
                'ordering': ['asset', 'platform', 'number_of_nights', 'reservation_number'],
            },
        ),
        migrations.CreateModel(
            name='FileHollyDaysReservation',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.file')),
                ('access_to_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RE_hollydays_reservation_files', to='real_estate.hollydaysreservation')),
            ],
            bases=('real_estate.file',),
        ),
        migrations.CreateModel(
            name='FileHollyDaysPlatform',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.file')),
                ('access_to_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RE_hollydays_platform_files', to='real_estate.hollydaysplatform')),
            ],
            bases=('real_estate.file',),
        ),
    ]
