# Generated by Django 4.1.6 on 2023-07-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_hollydaysplatform_hollydaysreservation_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='hollydaysreservation',
        #     name='number_of_nights',
        #     field=models.SmallIntegerField(blank=True, null=True),
        # ),
    ]
