# Generated by Django 4.1.6 on 2023-07-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_alter_hollydaysreservation_number_of_nights'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hollydaysreservation',
            options={'ordering': ['asset', 'platform', 'reservation_number'], 'verbose_name_plural': 'Hollydays Reservations'},
        ),
        migrations.RemoveField(
            model_name='hollydaysreservation',
            name='number_of_nights',
        ),
    ]
