# Generated by Django 4.1.6 on 2023-07-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0008_alter_hollydaysreservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hollydaysreservation',
            name='number_of_nights',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
