# Generated by Django 4.1.6 on 2023-07-12 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0009_hollydaysreservation_number_of_nights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hollydaysreservation',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='real_estate.asset'),
        ),
    ]
