# Generated by Django 4.1.6 on 2023-07-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0010_alter_hollydaysreservation_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitycontract',
            name='service',
            field=models.CharField(choices=[('waste management', 'waste management'), ('Electricity', 'Electricity'), ('Water', 'Water'), ('Internet', 'Internet'), ('Alarm', 'Alarm'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
