# Generated by Django 4.1.6 on 2023-07-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0011_alter_utilitycontract_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitycontract',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
