# Generated by Django 4.1.6 on 2023-07-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0012_alter_utilitycontract_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitycontract',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utility_supplier', to='real_estate.utilitysupplier'),
        ),
    ]
