# Generated by Django 4.1.6 on 2023-07-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0013_alter_utilitycontract_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitycontract',
            name='factures',
            field=models.JSONField(blank=True, help_text="ex: {'2023-07': 123.4, '2023-08': 23.67}", null=True),
        ),
    ]
