# Generated by Django 4.1.6 on 2023-07-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0014_utilitycontract_factures'),
    ]

    operations = [
        migrations.AddField(
            model_name='hollydaysreservation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
