# Generated by Django 4.1.6 on 2023-08-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0015_hollydaysreservation_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hollydaysreservation',
            name='cleaning',
            field=models.FloatField(blank=True, default=100, help_text='the price is inside the received money from the platform', null=True),
        ),
        migrations.AddField(
            model_name='hollydaysreservation',
            name='commission_other',
            field=models.FloatField(blank=True, default=0, help_text='For Fuerte, This is the Katia commission', null=True),
        ),
        migrations.AddField(
            model_name='hollydaysreservation',
            name='commission_platform',
            field=models.FloatField(blank=True, default=0, help_text='For RBnB the commission is already taken so it is 0, not for Booking', null=True),
        ),
    ]
