# Generated by Django 4.1.6 on 2023-08-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0016_hollydaysreservation_cleaning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilitycontract',
            name='factures',
        ),
        migrations.AddField(
            model_name='utilitycontract',
            name='monthly_price',
            field=models.FloatField(blank=True, default=0, help_text='If it is an annual price, divide it by twelve', null=True),
        ),
        migrations.AlterField(
            model_name='hollydaysreservation',
            name='cleaning',
            field=models.FloatField(blank=True, default=100, help_text='For R2R its 0. Else the price is inside the received money from the platform', null=True),
        ),
    ]
