# Generated by Django 4.1.6 on 2023-08-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0017_remove_utilitycontract_factures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitycontract',
            name='date_installation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilitycontract',
            name='installation_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
