# Generated by Django 4.1.6 on 2023-08-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0018_utilitycontract_date_installation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copromanagementcontract',
            name='monthly_price',
            field=models.FloatField(blank=True, default=0, help_text='If it is an annual price, divide it by twelve', null=True),
        ),
    ]
