# Generated by Django 4.1.6 on 2023-08-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0019_copromanagementcontract_monthly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitycontract',
            name='payment_01',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='utilitycontract',
            name='payment_02',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='utilitycontract',
            name='payment_03',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='utilitycontract',
            name='payment_04',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='utilitycontract',
            name='payment_05',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='utilitycontract',
            name='payment_06',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='utilitycontract',
            name='payment_07',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='utilitycontract',
            name='payment_08',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='utilitycontract',
            name='payment_09',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='utilitycontract',
            name='payment_10',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='utilitycontract',
            name='payment_11',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='utilitycontract',
            name='payment_12',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
