# Generated by Django 4.1.6 on 2023-08-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0020_utilitycontract_payment_01_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copromanagementcontract',
            name='year',
            field=models.SmallIntegerField(blank=True, default=2023, null=True),
        ),
        migrations.AddField(
            model_name='utilitycontract',
            name='year',
            field=models.SmallIntegerField(blank=True, default=2023, null=True),
        ),
    ]
