# Generated by Django 4.1.6 on 2023-08-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0021_copromanagementcontract_year_utilitycontract_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilitycontract',
            old_name='payment_01',
            new_name='payment_1',
        ),
        migrations.RenameField(
            model_name='utilitycontract',
            old_name='payment_02',
            new_name='payment_2',
        ),
        migrations.RenameField(
            model_name='utilitycontract',
            old_name='payment_03',
            new_name='payment_3',
        ),
        migrations.RenameField(
            model_name='utilitycontract',
            old_name='payment_04',
            new_name='payment_4',
        ),
        migrations.RenameField(
            model_name='utilitycontract',
            old_name='payment_05',
            new_name='payment_5',
        ),
        migrations.RenameField(
            model_name='utilitycontract',
            old_name='payment_06',
            new_name='payment_6',
        ),
        migrations.RenameField(
            model_name='utilitycontract',
            old_name='payment_07',
            new_name='payment_7',
        ),
        migrations.RenameField(
            model_name='utilitycontract',
            old_name='payment_08',
            new_name='payment_8',
        ),
        migrations.RenameField(
            model_name='utilitycontract',
            old_name='payment_09',
            new_name='payment_9',
        ),
    ]
