# Generated by Django 4.1.6 on 2023-08-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0022_rename_payment_01_utilitycontract_payment_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_location_commission_bill',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
