# Generated by Django 4.1.6 on 2024-05-03 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0026_alter_utilitysupplier_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['asset', 'bill_name', 'date', 'total_price'], 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='asset',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='real_estate.asset'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='client_name',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_tax_deductible',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='hollydaysreservation',
            name='asset',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='real_estate.asset'),
        ),
    ]
