# Generated by Django 4.1.6 on 2024-06-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0029_alter_filebill_access_to_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_comment',
            field=models.CharField(blank=True, help_text='Give a meaningfull description of this bill. It will be used for tax deduction', max_length=50, null=True),
        ),
    ]
