# Generated by Django 4.1.6 on 2023-06-20 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('ID card', 'ID card'), ('Passport', 'Passport'), ('driving licence', 'driving licence'), ('ticket', 'ticket'), ('other', 'other')], max_length=50, null=True)),
                ('comment', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.FileField(upload_to='static/files')),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.PositiveIntegerField(null=True)),
                ('site_app_company', models.CharField(blank=True, help_text='ex: myfoncia.com', max_length=70, null=True)),
            ],
            options={
                'verbose_name_plural': 'Insurance Companies',
                'ordering': ['name', 'phone_number'],
            },
        ),
        migrations.CreateModel(
            name='FileDocument',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrative.file')),
            ],
            bases=('administrative.file',),
        ),
        migrations.CreateModel(
            name='FileInsuranceContract',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrative.file')),
            ],
            bases=('administrative.file',),
        ),
        migrations.CreateModel(
            name='InsuranceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Real Estate insurance', 'Real Estate insurance'), ('Transportation insurance', 'Transportation insurance'), ('Person insurance', 'Person insurance')], max_length=50, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('is_insurance_active', models.BooleanField(blank=True, null=True)),
                ('personal_email_used', models.EmailField(blank=True, max_length=254, null=True)),
                ('annual_price', models.JSONField(blank=True, help_text="ex: {'2020': 400, '2021': 400, ...}", null=True)),
                ('coverage', models.JSONField(blank=True, help_text='{"bricolage": "3 heures", ...}', null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='administrative.insurancecompany')),
                ('person', models.ForeignKey(blank=True, help_text='Fill only if type = Person insurance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_contract', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Insurances',
                'ordering': ['company', 'type', 'annual_price'],
            },
        ),
    ]
