# Generated by Django 4.1.6 on 2023-06-20 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative', '0001_initial'),
        ('transportation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecontract',
            name='real_estate_asset',
            field=models.ForeignKey(blank=True, help_text='Fill only if type = Real Estate insurance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_contract', to='real_estate.asset'),
        ),
        migrations.AddField(
            model_name='insurancecontract',
            name='transportation_asset',
            field=models.ForeignKey(blank=True, help_text='Fill only if type = Transportation insurance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_contract', to='transportation.asset'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileinsurancecontract',
            name='access_to_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_contract_files', to='administrative.insurancecontract'),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='access_to_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='administrative.document'),
        ),
    ]
