# Generated by Django 4.1.6 on 2023-06-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0003_alter_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecompany',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
