# Generated by Django 4.1.6 on 2023-06-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_alter_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
