# Generated by Django 4.1.6 on 2023-08-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_tax_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='annual_price',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='payment_proof',
        ),
        migrations.AddField(
            model_name='tax',
            name='real_estate_tax_type',
            field=models.CharField(blank=True, choices=[('IVI', 'IVI'), ('Dustbin', 'Dustbin'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
