# Generated by Django 4.1.6 on 2023-08-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_remove_tax_annual_price_remove_tax_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='yearly_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
