# Generated by Django 4.1.6 on 2023-11-11 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.FileField(upload_to='static/files/')),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_name', models.CharField(help_text='Give a meaningfull name at this bill', max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, help_text='price including tax', null=True)),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_bill', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bills',
                'ordering': ['client_name', 'bill_name', 'date', 'total_price', 'is_paid'],
            },
        ),
        migrations.CreateModel(
            name='FileBill',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='health.file')),
                ('access_to_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_bill_files', to='health.bill')),
            ],
            bases=('health.file',),
        ),
    ]
