# Generated by Django 4.1.6 on 2023-11-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['client_name', 'bill_name', 'date', 'total_price', 'is_paid', 'is_asked_by_us'], 'verbose_name_plural': 'Bills'},
        ),
        migrations.AddField(
            model_name='bill',
            name='is_asked_by_us',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
