# Generated by Django 4.1.6 on 2023-11-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_alter_bill_options_bill_is_asked_by_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalMedecine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_issue', models.CharField(max_length=200, null=True)),
                ('classic_medecines', models.JSONField(blank=True, help_text="ex: {'medecine 1': 'details', 'medecine 2': 'details'}", null=True)),
                ('natural_medecines', models.JSONField(blank=True, help_text="ex: {'medecine 1': 'details', 'medecine 2': 'details'}", null=True)),
                ('comments', models.JSONField(blank=True, help_text="ex: {'comment 1': 'details', 'comment 2': 'details'}", null=True)),
            ],
            options={
                'verbose_name_plural': 'Natural Medecines',
                'ordering': ['health_issue'],
            },
        ),
        migrations.CreateModel(
            name='FileHealthIssue',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='health.file')),
                ('access_to_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_medecine_files', to='health.naturalmedecine')),
            ],
            bases=('health.file',),
        ),
    ]
