# Generated by Django 4.1.6 on 2023-11-24 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_naturalmedecine_filehealthissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileProduct',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='health.file')),
            ],
            bases=('health.file',),
        ),
        migrations.CreateModel(
            name='FileSymptom',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='health.file')),
            ],
            bases=('health.file',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('natural', models.BooleanField(null=True)),
                ('child_use', models.BooleanField(null=True)),
                ('adult_use', models.BooleanField(null=True)),
                ('min_age', models.CharField(blank=True, max_length=200, null=True)),
                ('source_info', models.CharField(blank=True, max_length=200, null=True)),
                ('date_info', models.DateField(blank=True, null=True)),
                ('composition', models.CharField(blank=True, max_length=200, null=True)),
                ('interests', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.JSONField(blank=True, help_text='ex: {"comment 1": "details", "comment 2": "details"}', null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['name', 'natural', 'child_use', 'min_age'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('child', models.BooleanField(null=True)),
                ('adult', models.BooleanField(null=True)),
                ('comments', models.JSONField(blank=True, help_text='ex: {"comment 1": "details", "comment 2": "details"}', null=True)),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='health.product')),
            ],
            options={
                'verbose_name_plural': 'Symptoms',
                'ordering': ['name', 'adult', 'child'],
            },
        ),
        migrations.DeleteModel(
            name='FileHealthIssue',
        ),
        migrations.DeleteModel(
            name='NaturalMedecine',
        ),
        migrations.AddField(
            model_name='filesymptom',
            name='access_to_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_symptom', to='health.symptom'),
        ),
        migrations.AddField(
            model_name='fileproduct',
            name='access_to_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_product', to='health.product'),
        ),
    ]
