# Generated by Django 4.1.6 on 2023-11-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_fileproduct_filesymptom_product_symptom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='products',
        ),
        migrations.AddField(
            model_name='symptom',
            name='products',
            field=models.ManyToManyField(related_name='product', to='health.product'),
        ),
    ]
