# Generated by Django 4.1.6 on 2023-06-20 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, help_text='69 RUE DU PORT', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('IBAN', models.CharField(max_length=40, null=True)),
                ('BIC', models.CharField(blank=True, max_length=20, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('closing_account_date', models.DateField(blank=True, null=True)),
                ('is_account_open', models.BooleanField(default=True, null=True)),
                ('value_on_31_12', models.JSONField(blank=True, help_text="ex: {'2020': 1234.65, '2021': 2367.8}", null=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='finances.bank')),
                ('titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['bank__name', 'is_account_open', 'IBAN'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.FileField(upload_to='static/files')),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('CCV', models.DateField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='finances.bankaccount')),
            ],
            options={
                'verbose_name_plural': 'Bank Cards',
                'ordering': ['bank_account__bank__name', 'name', 'card_number', 'ending_date', 'CCV'],
            },
        ),
        migrations.CreateModel(
            name='FileCard',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.file')),
                ('access_to_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BankCard_files', to='finances.bankcard')),
            ],
            bases=('finances.file',),
        ),
        migrations.CreateModel(
            name='FileAccount',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.file')),
                ('access_to_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BankAccount_files', to='finances.bankaccount')),
            ],
            bases=('finances.file',),
        ),
    ]
