# Generated by Django 4.1.6 on 2023-10-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_file_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='finances.bankaccount')),
            ],
            options={
                'verbose_name_plural': 'Bank Account Reports',
                'ordering': ['bank_account', 'date'],
            },
        ),
        migrations.CreateModel(
            name='FileAccountReport',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.file')),
                ('access_to_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BankAccountReport_files', to='finances.bankaccountreport')),
            ],
            bases=('finances.file',),
        ),
    ]
