# Generated by Django 4.1.6 on 2023-10-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_bankaccountreport_fileaccountreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccountreport',
            name='access_to_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FileAccountReport', to='finances.bankaccountreport'),
        ),
    ]
