# Generated by Django 4.1.6 on 2024-05-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_fileaccountreport_access_to_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='CCV',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
